
services:
  db:
    image: postgres:15-alpine
    container_name: res-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - res-network
  pgadmin:
    image: dpage/pgadmin4
    container_name: res-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - res-network

  
  redis:
    image: redis:alpine
    container_name: res-redis
    ports:
      - "6379:6379"
    networks:
      - res-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: res-api
    ports:
      - "5000:5000"
    env_file:
      - ./api/.env
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_USE_SSL: "false"
      MINIO_PUBLIC_ENDPOINT: localhost
      MINIO_PUBLIC_PORT: 9000
      MINIO_PUBLIC_USE_SSL: "false"
      MINIO_REGION: "us-east-1"
    depends_on:
      - db
      - redis
      - minio
    networks:
      - res-network
  minio:
    image: minio/minio
    container_name: res-minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - res-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: res-client
    ports:
      - "4200:4200" 
    environment:
      # Browser uses localhost; Next server (inside container) uses service DNS name
      NEXT_PUBLIC_API_URL: http://localhost:5000
      API_INTERNAL_URL: http://api:5000
    depends_on:
      - api
    networks:
      - res-network

volumes:
  postgres_data:
  minio_data:

networks:
  res-network:
