server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: res-api
    static_configs:
      - targets: [localhost]
        labels:
          job: res-api
          __path__: /var/log/api/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            context: context
            requestId: requestId
            userId: userId
            userEmail: userEmail
            phase: phase
            method: method
            url: url
            statusCode: statusCode
      - labels:
          level:
          context:
          phase:
          method:
          statusCode:

  - job_name: docker-containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container_name'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'
    pipeline_stages:
      - docker: {}
      - match:
          selector: '{container_name=~"res-(db|minio).*"}'
          stages:
            - regex:
                expression: '(?P<level>INFO|ERROR|WARN|DEBUG)'
            - labels:
                level:
